////////////////////////////////////////////////////////////////////////
// Class:       CoherentPionAna
// Module Type: analyzer
// File:        CoherentPionAna_module.cc
//
// Generated at Tue May 16 17:21:02 2017 by Ilker Parmaksiz using artmod
// from cetpkgsupport v1_11_00.
////////////////////////////////////////////////////////////////////////

#include "art/Framework/Core/EDAnalyzer.h"
#include "art/Framework/Core/ModuleMacros.h"
#include "art/Framework/Principal/Event.h"
#include "art/Framework/Principal/Handle.h"
#include "art/Framework/Principal/Run.h"
#include "art/Framework/Principal/SubRun.h"
#include "fhiclcpp/ParameterSet.h"
#include "messagefacility/MessageLogger/MessageLogger.h"


class CoherentPionAna;

class CoherentPionAna : public art::EDAnalyzer {
public:
  explicit CoherentPionAna(fhicl::ParameterSet const & p);
  // The destructor generated by the compiler is fine for classes
  // without bare pointers or other resource use.

  // Plugins should not be copied or assigned.
  CoherentPionAna(CoherentPionAna const &) = delete;
  CoherentPionAna(CoherentPionAna &&) = delete;
  CoherentPionAna & operator = (CoherentPionAna const &) = delete;
  CoherentPionAna & operator = (CoherentPionAna &&) = delete;

  // Required functions.
  void analyze(art::Event const & e) override;

  // Selected optional functions.
  void beginJob() override;
  void beginRun(art::Run const & r) override;
  void beginSubRun(art::SubRun const & sr) override;
  void endJob() override;
  void endRun(art::Run const & r) override;
  void endSubRun(art::SubRun const & sr) override;
  void reconfigure(fhicl::ParameterSet const & p) override;
  void respondToCloseInputFile(art::FileBlock const & fb) override;
  void respondToCloseOutputFiles(art::FileBlock const & fb) override;
  void respondToOpenInputFile(art::FileBlock const & fb) override;
  void respondToOpenOutputFiles(art::FileBlock const & fb) override;

private:

  // Declare member data here.

};


CoherentPionAna::CoherentPionAna(fhicl::ParameterSet const & p)
  :
  EDAnalyzer(p)  // ,
 // More initializers here.
{}

void CoherentPionAna::analyze(art::Event const & e)
{
  // Implementation of required member function here.
}

void CoherentPionAna::beginJob()
{
  // Implementation of optional member function here.
}

void CoherentPionAna::beginRun(art::Run const & r)
{
  // Implementation of optional member function here.
}

void CoherentPionAna::beginSubRun(art::SubRun const & sr)
{
  // Implementation of optional member function here.
}

void CoherentPionAna::endJob()
{
  // Implementation of optional member function here.
}

void CoherentPionAna::endRun(art::Run const & r)
{
  // Implementation of optional member function here.
}

void CoherentPionAna::endSubRun(art::SubRun const & sr)
{
  // Implementation of optional member function here.
}

void CoherentPionAna::reconfigure(fhicl::ParameterSet const & p)
{
  // Implementation of optional member function here.
}

void CoherentPionAna::respondToCloseInputFile(art::FileBlock const & fb)
{
  // Implementation of optional member function here.
}

void CoherentPionAna::respondToCloseOutputFiles(art::FileBlock const & fb)
{
  // Implementation of optional member function here.
}

void CoherentPionAna::respondToOpenInputFile(art::FileBlock const & fb)
{
  // Implementation of optional member function here.
}

void CoherentPionAna::respondToOpenOutputFiles(art::FileBlock const & fb)
{
  // Implementation of optional member function here.
}

DEFINE_ART_MODULE(CoherentPionAna)
